## Algunas funciones de ASE

In [1]:
from ase import Atoms

# Ejemplo, construcción de una molecula de CO
d = 1.1
# ASE ya sabe los elementos
co = Atoms('CO', positions=[(0, 0, 0), (0, 0, d)])

#Hola
#Hola otra vez
#Hola tengo hambre
#Va a llover
#anvorgesa

In [2]:
from ase import Atoms
from ase.visualize import view


d = 2.9
L = 10.0
#visualización de la celda sólo se añade el argumento cell con las dimensiones
wire = Atoms('Au',
             positions=[[0, L / 2, L / 2]],
             cell=[d, L, L],
             pbc=[1, 0, 0])
view(wire, viewer='x3d')

In [ ]:
from ase import Atoms
from ase.build import fcc111, add_adsorbate, bulk
from ase.io import read, write

adsorbate = Atoms('COO')
adsorbate[1].z = 1.1
a = 3.61
slab = fcc111('Cu', (2, 2, 3), a=a, vacuum=7.0)
add_adsorbate(slab, adsorbate, 1.8, 'ontop')

### Lectura prueba de archivo de grafeno

In [25]:
from ase.io import read
graphene = read('g90_v.in')

In [26]:
# Info
print("\nNúmero de átomos:", len(graphene))
print("\nSímbolos de los átomos:", graphene.get_chemical_symbols())
print("\nPosiciones de los átomos:\n", graphene.get_positions())


Número de átomos: 98

Símbolos de los átomos: ['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C']

Posiciones de los átomos:
 [[-7.0740000e-03 -7.5720000e-03  2.5900000e-04]
 [ 1.1000570e+00  6.3198800e-01 -1.0600000e-04]
 [ 1.0991610e+00  1.9102310e+00  4.5000000e-04]
 [ 2.2069280e+00  2.5497920e+00  2.0820000e-03]
 [ 2.2065680e+00  3.8292650e+00  3.5860000e-03]
 [ 3.3116970e+00  4.4690600e+00  4.0440000e-03]
 [ 3.3115060e+00  5.7519460e+00  5.6180000e-03]
 [ 4.4178300e+00  6.3946040e+00  6.5270000e-03]
 [ 4.4213090e+00  7.6740320e+00  7.9720000e-03]
 [

In [27]:
positions = graphene.get_positions()
print(positions.shape)

(98, 3)


### Dataset, dinamica de graphene

In [28]:
from ase.io import read
import numpy as np

# Lectura de los archivos de coordenadas
graphene_090 = read('geometry090.in')
graphene_096 = read('geometry096.in')
graphene_100 = read('geometry100.in')
graphene_102 = read('geometry102.in')
graphene_108 = read('geometry108.in')
graphene_115 = read('geometry115.in')

# Obtención de las posiciones del grafeno
positions_090 = graphene_090.get_positions()
positions_096 = graphene_096.get_positions()
positions_100 = graphene_100.get_positions()
positions_102 = graphene_102.get_positions()
positions_108 = graphene_108.get_positions()
positions_115 = graphene_115.get_positions()

#print(positions_090.shape, positions_096.shape, positions_100.shape, positions_102.shape, positions_108.shape, positions_115.shape)

# Uniendo los arrays
positions_graphene = np.concatenate((positions_090, positions_096, positions_100, positions_102, positions_108, positions_115))
print('Shape del array concatenado:', positions_graphene.shape)
#Reshapeando los arrays
positions_graphene = positions_graphene.reshape(6, 98, 3)
print('\nShape del nuevo array:', positions_graphene.shape)
print('\n', positions_graphene)

Shape del array concatenado: (588, 3)

Shape del nuevo array: (6, 98, 3)

 [[[-7.0740000e-03 -7.5720000e-03  2.5900000e-04]
  [ 1.1000570e+00  6.3198800e-01 -1.0600000e-04]
  [ 1.0991610e+00  1.9102310e+00  4.5000000e-04]
  ...
  [ 1.9937942e+01  1.0231026e+01  7.4100000e-03]
  [ 1.9938920e+01  1.1508832e+01  4.0450000e-03]
  [ 2.1048171e+01  1.2149160e+01  2.9200000e-03]]

 [[-7.5210000e-03 -8.0510000e-03  2.7500000e-04]
  [ 1.1695780e+00  6.7192800e-01 -1.1300000e-04]
  [ 1.1686250e+00  2.0309520e+00  4.7800000e-04]
  ...
  [ 2.1197964e+01  1.0877599e+01  7.8780000e-03]
  [ 2.1199004e+01  1.2236158e+01  4.3000000e-03]
  [ 2.2378357e+01  1.2916953e+01  3.1040000e-03]]

 [[-7.8600000e-03 -8.4140000e-03  2.8800000e-04]
  [ 1.2222860e+00  7.0220900e-01 -1.1800000e-04]
  [ 1.2212900e+00  2.1224790e+00  4.9900000e-04]
  ...
  [ 2.2153269e+01  1.1367807e+01  8.2330000e-03]
  [ 2.2154356e+01  1.2787591e+01  4.4940000e-03]
  [ 2.3386856e+01  1.3499066e+01  3.2440000e-03]]

 [[-7.9970000e-03 -

In [29]:
# Pruebas pa ver si lo hice bn
print('El array completo de 0.90 es:\n', positions_090)
print('\nEl renglón 0 del array es:', positions_090[0])

El array completo de 0.90 es:
 [[-7.0740000e-03 -7.5720000e-03  2.5900000e-04]
 [ 1.1000570e+00  6.3198800e-01 -1.0600000e-04]
 [ 1.0991610e+00  1.9102310e+00  4.5000000e-04]
 [ 2.2069280e+00  2.5497920e+00  2.0820000e-03]
 [ 2.2065680e+00  3.8292650e+00  3.5860000e-03]
 [ 3.3116970e+00  4.4690600e+00  4.0440000e-03]
 [ 3.3115060e+00  5.7519460e+00  5.6180000e-03]
 [ 4.4178300e+00  6.3946040e+00  6.5270000e-03]
 [ 4.4213090e+00  7.6740320e+00  7.9720000e-03]
 [ 5.5321770e+00  8.3154980e+00  8.7270000e-03]
 [ 5.5337010e+00  9.5923540e+00  9.4190000e-03]
 [ 6.6419850e+00  1.0231825e+01  8.8110000e-03]
 [ 6.6419870e+00  1.1510709e+01  5.1510000e-03]
 [ 7.7494580e+00  1.2149159e+01  2.9460000e-03]
 [ 2.2092750e+00 -8.3520000e-03  1.7400000e-04]
 [ 3.3163250e+00  6.2959200e-01  3.3600000e-04]
 [ 3.3148180e+00  1.9098360e+00  1.6910000e-03]
 [ 4.4212980e+00  2.5471000e+00  1.8910000e-03]
 [ 4.4179550e+00  3.8264310e+00  3.3420000e-03]
 [ 5.5247750e+00  4.4653980e+00 -3.1740000e-03]
 [ 5.5244

In [30]:
print('Primera posición 0.90', positions_090[0])
print('Posición array_weno:', positions_graphene[0][0])

print('\nPrimera posición 0.96', positions_096[0])
print('Posición array_weno:', positions_graphene[1][0])

print('\nPrimera posición 1.00', positions_100[0])
print('Posición array_weno:', positions_graphene[2][0])

print('\nPrimera posición 1.02', positions_102[0])
print('Posición array_weno:', positions_graphene[3][0])

print('\nPrimera posición 1.08', positions_108[0])
print('Posición array_weno:', positions_graphene[4][0])

print('\nShape del array weno', positions_graphene.shape)

Primera posición 0.90 [-0.007074 -0.007572  0.000259]
Posición array_weno: [-0.007074 -0.007572  0.000259]

Primera posición 0.96 [-0.007521 -0.008051  0.000275]
Posición array_weno: [-0.007521 -0.008051  0.000275]

Primera posición 1.00 [-0.00786  -0.008414  0.000288]
Posición array_weno: [-0.00786  -0.008414  0.000288]

Primera posición 1.02 [-0.007997 -0.00856   0.000293]
Posición array_weno: [-0.007997 -0.00856   0.000293]

Primera posición 1.08 [-0.008502 -0.009101  0.000311]
Posición array_weno: [-0.008502 -0.009101  0.000311]

Shape del array weno (6, 98, 3)


### Creación de un pequeño dataset de Energías y Fuerzas

In [31]:
import numpy as np

#Array de Energías
Energies = np.array([[300, 301, 302, 305, 309, 330]])
Energies = Energies.reshape(6,1)
print(Energies)

print('\nShape del array de Energías:', Energies.shape)

[[300]
 [301]
 [302]
 [305]
 [309]
 [330]]

Shape del array de Energías: (6, 1)


In [32]:
# Ejemplo de construcción de array de fuerzas
i, j = 1, 1
fp2 = []
for j in range(6):
    fp=[]
    for i in range(98):
        i+=1
        array1 = np.random.uniform(50, 200, 3)
        array1 = array1.tolist()
        fp.append(array1)
    fp2.append(fp)
    j+=1

Forces = np.array(fp2)
print(Forces.shape)
#print(fp2)

(6, 98, 3)


### Creación del array de z

In [33]:
num_elementos = 98  # Un arreglo de 98 elementos
value = 6     # Valor constante
z = np.full(num_elementos, value)
print(z.shape)


(98,)


### Pruebas de arrays

In [34]:
print('El shape de posiciones es:', positions_graphene.shape)
print('\nEl array es:', positions_graphene)

El shape de posiciones es: (6, 98, 3)

El array es: [[[-7.0740000e-03 -7.5720000e-03  2.5900000e-04]
  [ 1.1000570e+00  6.3198800e-01 -1.0600000e-04]
  [ 1.0991610e+00  1.9102310e+00  4.5000000e-04]
  ...
  [ 1.9937942e+01  1.0231026e+01  7.4100000e-03]
  [ 1.9938920e+01  1.1508832e+01  4.0450000e-03]
  [ 2.1048171e+01  1.2149160e+01  2.9200000e-03]]

 [[-7.5210000e-03 -8.0510000e-03  2.7500000e-04]
  [ 1.1695780e+00  6.7192800e-01 -1.1300000e-04]
  [ 1.1686250e+00  2.0309520e+00  4.7800000e-04]
  ...
  [ 2.1197964e+01  1.0877599e+01  7.8780000e-03]
  [ 2.1199004e+01  1.2236158e+01  4.3000000e-03]
  [ 2.2378357e+01  1.2916953e+01  3.1040000e-03]]

 [[-7.8600000e-03 -8.4140000e-03  2.8800000e-04]
  [ 1.2222860e+00  7.0220900e-01 -1.1800000e-04]
  [ 1.2212900e+00  2.1224790e+00  4.9900000e-04]
  ...
  [ 2.2153269e+01  1.1367807e+01  8.2330000e-03]
  [ 2.2154356e+01  1.2787591e+01  4.4940000e-03]
  [ 2.3386856e+01  1.3499066e+01  3.2440000e-03]]

 [[-7.9970000e-03 -8.5600000e-03  2.930000

In [35]:
print('El shape de Energías es:', Energies.shape)
print('\nEl array es:', Energies)

El shape de Energías es: (6, 1)

El array es: [[300]
 [301]
 [302]
 [305]
 [309]
 [330]]


In [36]:
print('El shape de Fuerzas es:', Forces.shape)
print('\nEl array es:', Forces)

El shape de Fuerzas es: (6, 98, 3)

El array es: [[[169.93544348 136.43525299 158.52302916]
  [124.21320922 174.05559603 113.50295868]
  [ 97.16341615 118.47726876 181.26946427]
  ...
  [ 71.69343135 168.61103503 196.06066968]
  [135.95047896  79.92573067  56.63588291]
  [ 81.96948106  68.16415034 146.1233138 ]]

 [[192.47526261 108.2935594  146.74549883]
  [ 57.60061913 100.43151931 171.22805741]
  [ 88.68486792 188.39697221  74.18692914]
  ...
  [186.10017236 116.25725778 121.78493096]
  [135.19460774 149.21236145 170.54360389]
  [ 61.99255333 191.55374033  69.68414276]]

 [[101.47831031 152.75924304 131.64269201]
  [114.05829195 197.487289   161.02783725]
  [133.96457411  85.6090001   57.41814602]
  ...
  [ 50.32332343 152.98009983  87.75025045]
  [110.91157221 192.52666753 179.76855872]
  [135.69102943 198.76865583  98.04399841]]

 [[123.76700016  80.07944063  98.50142397]
  [103.29216973 189.80172811 116.88404351]
  [153.90445227  97.90434396 199.01085968]
  ...
  [ 92.95008422  8

In [37]:
print('El shape de z es:', z.shape)
print('\nEl array es:', z)

El shape de z es: (98,)

El array es: [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]


### Checar enlaces graphene

In [38]:
from ase.io import read
bonds_graph = read('graph_prueba.xyz')
view(bonds_graph, viewer='x3d')

In [39]:
# Tratar de seleccionar un anillo de grafeno
# no funciona
from ase.io import read, write

# Leer la estructura completa desde un archivo .xyz
structure = read('graph_prueba.xyz')

# Seleccionar los primeros 6 átomos
selected_atoms = structure[:10]
view(selected_atoms, viewer = 'x3d' )

"""
# Guardar la nueva estructura con solo 6 átomos en un archivo nuevo
write('reduced_structure.xyz', selected_atoms)

# Imprimir la nueva estructura para verificar
print("Nueva estructura con solo 6 átomos:")
print(selected_atoms)
"""

'\n# Guardar la nueva estructura con solo 6 átomos en un archivo nuevo\nwrite(\'reduced_structure.xyz\', selected_atoms)\n\n# Imprimir la nueva estructura para verificar\nprint("Nueva estructura con solo 6 átomos:")\nprint(selected_atoms)\n'

In [40]:
# Tratando de obtener los indices de los atomos
# No funciona

from ase.io import read

# Leer la estructura desde un archivo .xyz
# archivo de Vesta
structure = read('graph_prueba.xyz')

# Obtener los índices de los átomos
atom_indices = [atom.index for atom in structure]
pos_prueba = structure.get_positions()

# Imprimir los índices de los átomos
print("Índices de los átomos:")
print(atom_indices)

print(len(pos_prueba))

Índices de los átomos:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127]
128


In [41]:
# Tratando de hacer con archivos originales
# graphene_090
# obtención de indices de los atomos

print(graphene_090)

atom_indices = [atom.index for atom in graphene_090]
print("Índices de los átomos:")
print(atom_indices)
#pos_prueba = structure.get_positions()


Atoms(symbols='C98', pbc=True, cell=[[15.513656, 0.0, 0.0], [7.756821, 13.435202, 0.0], [0.0, 0.0, 59.999966]])
Índices de los átomos:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]


### Tutorial para saber enlaces

In [42]:
# Ejemplo de conectividad de atomos en una molecula
from scipy import sparse
from ase.build import molecule
from ase.neighborlist import get_connectivity_matrix
from ase.neighborlist import natural_cutoffs
from ase.neighborlist import NeighborList

In [43]:
# Construye una molecula de etanol
mol = molecule('CH3CH2OH')
# Calcula los radios de corte (cutoffs) para los pares de átomos en un sistema
# Determina los radios de corte naturales antes de realizar cálculos más detallados o simulaciones
# Toma un objeto de tipo Atoms y devuelve una lista de radios de corte
# Estos radios se calculan típicamente en función de las propiedades atómicas y las configuraciones geométricas del sistema.
cutoffs = natural_cutoffs(mol)
print('Los radios de corte naturales son:', cutoffs)
# Cutoffs: Cada valor en esta lista define el radio de corte para cada átomo en el sistema
# Self_interactions: Booleano que indica si un átomo puede considerarse vecino de sí mismo.
# Bothways: Booleano que indica si la lista de vecinos debe ser simétrica.
# Si es True (por defecto), si el átomo A considera al átomo B como vecino, entonces B también considerará a A como vecino.
neighbor_list = NeighborList(cutoffs, self_interaction=False, bothways=True)
neighbor_list.update(mol)

Los radios de corte naturales son: [0.76, 0.76, 0.66, 0.31, 0.31, 0.31, 0.31, 0.31, 0.31]


True

In [46]:
# hace la matriz de conexiones entre atomos
matrix = neighbor_list.get_connectivity_matrix()
# Función de Scipy
# sparse.csgraph.connected_components(matrix)
# Encuentra componentes conexos de un grafo representado por una matriz dispersa (sparse matrix)
# Los componentes conexos de un grafo son subgrafos en los que hay un camino entre cualquier par de nodos dentro del mismo subgrafo,
# y no hay camino hacia ningún nodo fuera del subgrafo.
# args:
# sparse matrix
# directed: Un booleano que indica si el grafo es dirigido (True) o no dirigido (False). Por defecto es True
# connection: Especifica el tipo de conexión a considerar para grafos no dirigidos. Puede ser 'weak' o 'strong'.
# Este parámetro solo tiene efecto si directed=True. Por defecto es 'weak'
# return_labels: Booleano que indica si se deben devolver las etiquetas de los componentes. Por defecto (True)
# Return of the func:
# n_components: El número de componentes conexos en el grafo.
# labels: array donde el índice representa un nodo del grafo y el valor en ese índice representa la etiqueta del componente conexo al que pertenece el nodo.
# Este array solo se devuelve si return_labels=True.
n_components, component_list = sparse.csgraph.connected_components(matrix)

idx = 1

molIdx = component_list[idx]

print("There are {} molecules in the system".format(n_components))
#There are 1 molecules in the system

print("Atom {} is part of molecule {}".format(idx, molIdx))
#Atom 1 is part of molecule 0

molIdxs = [i for i in range(len(component_list)) if component_list[i] == molIdx]
print("Atoms are part of molecule {}: {}".format(molIdx, molIdxs))
#Atoms are part of molecule 0: [0, 1, 2, 3, 4, 5, 6, 7, 8]

There are 1 molecules in the system
Atom 1 is part of molecule 0
Atoms are part of molecule 0: [0, 1, 2, 3, 4, 5, 6, 7, 8]


In [47]:
print(component_list)

[0 0 0 0 0 0 0 0 0]


In [48]:
idx = 1
molIdx = component_list[idx]
print(molIdx)

0


In [49]:
print(matrix.shape)
print(matrix)

(9, 9)
  (0, 1)	1
  (0, 6)	1
  (0, 7)	1
  (0, 8)	1
  (1, 2)	1
  (1, 4)	1
  (1, 5)	1
  (1, 0)	1
  (2, 3)	1
  (2, 1)	1
  (3, 2)	1
  (4, 1)	1
  (5, 1)	1
  (6, 0)	1
  (7, 0)	1
  (8, 0)	1


### Tutorial sparse matrix scipy

In [50]:
import scipy.sparse
import numpy as np

# Crear una matriz dispersa de 4x4 (16 elementos) todos 0
dok_matrix = scipy.sparse.dok_matrix((4, 4), dtype=float)
# Agregar algunos elementos puntuales a la matriz
dok_matrix[0, 1] = 3.0
dok_matrix[2, 3] = 5.0
dok_matrix[3, 3] = 7.0

In [51]:
# Coordenadas de matriz donde e elemento donde es 0
print(dok_matrix[0,0])

0.0


In [52]:
# Cambiar de sparse a dense:
dense_matrix = scipy.sparse.csr_matrix.todense(dok_matrix)
print(dense_matrix)

[[0. 3. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 5.]
 [0. 0. 0. 7.]]


### Solución de sistemas de ecuaciones lineales

Sistema de ecuaciones a resolver:

$$ x_{1} + x_{2} + 0 = 1 $$
$$ 0 + x_{2} + x_{3} = 4 $$
$$  x_{1} + 2x_{2} + 3x_{3} = 6 $$

En matrices:

$$ \begin{pmatrix}  1 & 1 & 0 \\ 0 & 1 & 1 \\ 1 & 2 & 3\end{pmatrix} 
\begin{pmatrix} x_{1}\\ x_{2}\\ x_{3}\end{pmatrix} = \begin{pmatrix} 1\\ 4\\ 6 \end{pmatrix}$$

La solución al sistema es:
$$\begin{pmatrix} x_{1}\\ x_{2}\\ x_{3}\end{pmatrix} = \begin{pmatrix}  1 & 1 & 0 \\ 0 & 1 & 1 \\ 1 & 2 & 3\end{pmatrix}^{-1} \begin{pmatrix} 1\\ 4\\ 6 \end{pmatrix}$$


In [53]:
# Sistema de ecuaciones
A = np.array([[1,1,0], [0,1,1], [1,2,3]])
y = np.array([1,4,6])
y = y.reshape(3,1)
# matriz inversa
Ainv = np.linalg.inv(A)
# multiplicación de matrices
x_inv = np.matmul(Ainv, y)
x_sol = np.linalg.solve(A, y)

print('la solución con inversa es:\n', x_inv)
print('la solucion con solve es:\n', x_sol)

la solución con inversa es:
 [[-2.5]
 [ 3.5]
 [ 0.5]]
la solucion con solve es:
 [[-2.5]
 [ 3.5]
 [ 0.5]]


### Listas de indices de ASE

In [54]:
print(component_list)
print(molIdxs)
print(molIdx)
print(labels)

[0 0 0 0 0 0 0 0 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
0


NameError: name 'labels' is not defined

In [ ]:
print(molIdxs)

In [55]:
# Otro ejemplo de sparse matrix
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import connected_components

# Definir una matriz de adyacencia para un grafo no dirigido
graph = np.array([[0, 1, 0, 0, 0],
                  [1, 0, 1, 0, 0],
                  [0, 1, 0, 0, 0],
                  [0, 0, 0, 0, 1],
                  [0, 0, 0, 1, 0]])

# Convertir la matriz a una matriz dispersa
sparse_graph = csr_matrix(graph)

# Encontrar los componentes conexos
n_components, labels = connected_components(csgraph=sparse_graph, directed=False)

#print(sparse_graph)
# Imprimir el número de componentes conexos
print(f"Number of connected components: {n_components}")

# Imprimir las etiquetas de los componentes conexos
print(f"Labels of connected components: {labels}")


Number of connected components: 2
Labels of connected components: [0 0 0 1 1]


In [56]:
print(molIdxs)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [57]:
import sys
print(sys.version)


3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]


### Tutorial construcción de idx y dst list

#### Prueba con etanol

#### Código General

In [58]:
from ase.io import read
from ase.visualize import view
from scipy import sparse
from ase.build import molecule
from ase.neighborlist import get_connectivity_matrix
from ase.neighborlist import natural_cutoffs
from ase.neighborlist import NeighborList
import scipy.sparse
import itertools

In [59]:
# Construye una molecula de etanol
mol = molecule('CH3CH2OH')
# Radios de corte naturales
cutoffs = natural_cutoffs(mol)
print('Los radios de corte naturales son:', cutoffs)
# Lista de vecinos para conocer sus conexiones
neighbor_list = NeighborList(cutoffs, self_interaction=False, bothways=True)
neighbor_list.update(mol)

Los radios de corte naturales son: [0.76, 0.76, 0.66, 0.31, 0.31, 0.31, 0.31, 0.31, 0.31]


True

In [60]:
# Matriz dispersa de enlaces
matrix_ethanol_sparse = neighbor_list.get_connectivity_matrix()
#print(matrix)

# Matriz dispersa a densa
matrix_ethanol_dense = scipy.sparse.csr_matrix.todense(matrix_ethanol_sparse)
#print(matrix_ethanol_dense)
print(matrix_ethanol_dense[0])
#print(matrix_ethanol_dense.shape)

# Obteniendo el primer renglón de la matriz densa
mp = matrix_ethanol_dense[0]
print(mp.shape)

[[0 1 0 0 0 0 1 1 1]]
(1, 9)


In [61]:
# Obteniendo las etiquetas de los vecinos para el átomo 0
nbrs = [i for i in range(len(matrix_ethanol_dense[:][:])) if matrix_ethanol_dense[0,i] == 1]
print(nbrs)
print(matrix_ethanol_dense[0,1])
print(type(nbrs))

[1, 6, 7, 8]
1
<class 'list'>


In [62]:
# Lista de los vecinos de cada átomo:
nbrs_total =[]
j = 0
for j in range(len(matrix_ethanol_dense[:][:])):
    nbrs=[]
    nbrs = [i for i in range(len(matrix_ethanol_dense[:][:])) if matrix_ethanol_dense[j,i] == 1]
    nbrs_total.append(nbrs)
    j+=1

# Impresión de los vecinos de cada átomo
# El indice de la lista corresponde al átomo de referencia
# Los elementos list[i] representa las etiquetas de los vecinos que tiene
print(nbrs_total)
print(len(nbrs_total))

[[1, 6, 7, 8], [0, 2, 4, 5], [1, 3], [2], [1], [1], [0], [0], [0]]
9


In [63]:
"""
nbrs_total[0]
# ciclo for normal
prueba = []
for i in range(len(nbrs_total[0])):
    prueba.append(0)
    i+=1

print(prueba)
"""

'\nnbrs_total[0]    \n# ciclo for normal\nprueba = []\nfor i in range(len(nbrs_total[0])):\n    prueba.append(0)\n    i+=1\n    \nprint(prueba)\n'

In [64]:
# Repetición del átomo de referencia por cada número de vecinos
prueba_cl = [0 for i in range(len(nbrs_total[0]))]
print(prueba_cl)

[0, 0, 0, 0]


#### dst_idx

In [65]:
# Construcción final de dst_idx
dst_idx = []
for j in range(len(nbrs_total)):
    prueba_cl = [j for i in range(len(nbrs_total[j]))]
    dst_idx.append(prueba_cl)

dst_idx = list(itertools.chain(*dst_idx))
print(dst_idx)
print(len(dst_idx))

[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 4, 5, 6, 7, 8]
16


#### src_idx

In [66]:
print(nbrs_total)
src_idx = list(itertools.chain(*nbrs_total))
print(src_idx)
print(len(src_idx))

[[1, 6, 7, 8], [0, 2, 4, 5], [1, 3], [2], [1], [1], [0], [0], [0]]
[1, 6, 7, 8, 0, 2, 4, 5, 1, 3, 2, 1, 1, 0, 0, 0]
16


### Pruebas para exportar datos

In [3]:
import numpy as np
dataset= np.load('graphene_prueba.npz')
print(dataset['R'])

[[[-7.0740000e-03 -7.5720000e-03  2.5900000e-04]
  [ 1.1000570e+00  6.3198800e-01 -1.0600000e-04]
  [ 1.0991610e+00  1.9102310e+00  4.5000000e-04]
  ...
  [ 1.9937942e+01  1.0231026e+01  7.4100000e-03]
  [ 1.9938920e+01  1.1508832e+01  4.0450000e-03]
  [ 2.1048171e+01  1.2149160e+01  2.9200000e-03]]

 [[-7.5210000e-03 -8.0510000e-03  2.7500000e-04]
  [ 1.1695780e+00  6.7192800e-01 -1.1300000e-04]
  [ 1.1686250e+00  2.0309520e+00  4.7800000e-04]
  ...
  [ 2.1197964e+01  1.0877599e+01  7.8780000e-03]
  [ 2.1199004e+01  1.2236158e+01  4.3000000e-03]
  [ 2.2378357e+01  1.2916953e+01  3.1040000e-03]]

 [[-7.8600000e-03 -8.4140000e-03  2.8800000e-04]
  [ 1.2222860e+00  7.0220900e-01 -1.1800000e-04]
  [ 1.2212900e+00  2.1224790e+00  4.9900000e-04]
  ...
  [ 2.2153269e+01  1.1367807e+01  8.2330000e-03]
  [ 2.2154356e+01  1.2787591e+01  4.4940000e-03]
  [ 2.3386856e+01  1.3499066e+01  3.2440000e-03]]

 [[-7.9970000e-03 -8.5600000e-03  2.9300000e-04]
  [ 1.2434920e+00  7.1439200e-01 -1.2000000e-

### Pruebas con funciones y listas idx's

In [8]:
from ase.io import read
from ase.visualize import view
from scipy import sparse
from ase.build import molecule
from ase.neighborlist import get_connectivity_matrix
from ase.neighborlist import natural_cutoffs
from ase.neighborlist import NeighborList
import scipy.sparse
import itertools

In [22]:
# Haciendo función
#def sof(x):

dataset = np.load('graphene_prueba.npz')
print(dataset.files)
#print(dataset)

graph_positions = dataset['R']

#print(graph_positions)

#cutoffs = natural_cutoffs(graph_positions)

['R', 'E', 'F', 'z']
